openapi: 3.0.3
info:
  title: Wound_IQ REST API
  description: Production-ready REST API for managing wound assessments
  version: 1.0.0
  contact:
    email: your.email@example.com

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: Health
    description: Health check endpoints
  - name: Patients
    description: Patient management operations
  - name: Clinicians
    description: Clinician management operations
  - name: Assessments
    description: Assessment management operations
  - name: Reports
    description: Reporting and analytics

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time

  /v1/patients:
    get:
      tags:
        - Patients
      summary: Get all patients
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPatientsResponse'

    post:
      tags:
        - Patients
      summary: Create a new patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePatientRequest'
      responses:
        '201':
          description: Patient created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/patients/{id}:
    get:
      tags:
        - Patients
      summary: Get patient by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Patient not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Patients
      summary: Update patient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePatientRequest'
      responses:
        '200':
          description: Patient updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'

    delete:
      tags:
        - Patients
      summary: Delete patient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Patient deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /v1/patients/{id}/history:
    get:
      tags:
        - Reports
      summary: Get patient wound history
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  patient_id:
                    type: integer
                  history:
                    type: array
                    items:
                      $ref: '#/components/schemas/WoundHistory'

  /v1/clinicians:
    get:
      tags:
        - Clinicians
      summary: Get all clinicians
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: page_size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response

    post:
      tags:
        - Clinicians
      summary: Create a new clinician
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClinicianRequest'
      responses:
        '201':
          description: Clinician created successfully

  /v1/clinicians/{id}:
    get:
      tags:
        - Clinicians
      summary: Get clinician by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response

    put:
      tags:
        - Clinicians
      summary: Update clinician
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClinicianRequest'
      responses:
        '200':
          description: Clinician updated successfully

    delete:
      tags:
        - Clinicians
      summary: Delete clinician
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Clinician deleted successfully

  /v1/assessments:
    get:
      tags:
        - Assessments
      summary: Get all assessments with filters
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: page_size
          in: query
          schema:
            type: integer
        - name: patient_id
          in: query
          schema:
            type: integer
        - name: clinician_id
          in: query
          schema:
            type: integer
        - name: start_date
          in: query
          schema:
            type: string
            format: date-time
        - name: end_date
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successful response

    post:
      tags:
        - Assessments
      summary: Create a simple assessment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAssessmentRequest'
      responses:
        '201':
          description: Assessment created successfully

  /v1/assessments/full:
    post:
      tags:
        - Assessments
      summary: Create a full assessment with all related data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullAssessmentRequest'
      responses:
        '201':
          description: Full assessment created successfully

  /v1/assessments/{id}:
    get:
      tags:
        - Assessments
      summary: Get assessment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response

    put:
      tags:
        - Assessments
      summary: Update assessment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAssessmentRequest'
      responses:
        '200':
          description: Assessment updated successfully

    delete:
      tags:
        - Assessments
      summary: Delete assessment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Assessment deleted successfully

  /v1/assessments/{id}/full:
    get:
      tags:
        - Reports
      summary: Get full assessment details
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullAssessmentResponse'

components:
  schemas:
    Patient:
      type: object
      properties:
        patient_id:
          type: integer
        full_name:
          type: string
        date_of_birth:
          type: string
          format: date-time
        gender:
          type: string
          enum: [Male, Female, Other]
        medical_record_number:
          type: string

    CreatePatientRequest:
      type: object
      required:
        - full_name
        - date_of_birth
        - gender
        - medical_record_number
      properties:
        full_name:
          type: string
          minLength: 2
          maxLength: 100
        date_of_birth:
          type: string
          format: date-time
        gender:
          type: string
          enum: [Male, Female, Other]
        medical_record_number:
          type: string
          minLength: 1
          maxLength: 50

    UpdatePatientRequest:
      type: object
      properties:
        full_name:
          type: string
        date_of_birth:
          type: string
          format: date-time
        gender:
          type: string
        medical_record_number:
          type: string

    CreateClinicianRequest:
      type: object
      required:
        - full_name
        - role
        - department
        - contact_info
        - license_number
      properties:
        full_name:
          type: string
        role:
          type: string
        department:
          type: string
        contact_info:
          type: string
        license_number:
          type: string

    UpdateClinicianRequest:
      type: object
      properties:
        full_name:
          type: string
        role:
          type: string
        department:
          type: string
        contact_info:
          type: string
        license_number:
          type: string

    CreateAssessmentRequest:
      type: object
      required:
        - clinician_id
        - patient_id
        - location
        - etiology
        - depth_of_injury
        - stage
        - chronicity
        - healing_status
      properties:
        clinician_id:
          type: integer
        patient_id:
          type: integer
        location:
          type: string
        etiology:
          type: string
        depth_of_injury:
          type: string
        stage:
          type: string
        chronicity:
          type: string
        healing_status:
          type: string
        return_to_clinic:
          type: boolean

    UpdateAssessmentRequest:
      type: object
      properties:
        location:
          type: string
        etiology:
          type: string
        depth_of_injury:
          type: string
        stage:
          type: string
        chronicity:
          type: string
        healing_status:
          type: string
        return_to_clinic:
          type: boolean

    FullAssessmentRequest:
      type: object
      required:
        - clinician_id
        - patient_id
        - location
        - etiology
        - depth_of_injury
        - stage
        - chronicity
        - healing_status
        - infection_pain
        - tissue_status
        - vitals
        - wound_condition
        - exudate
        - treatment
      properties:
        clinician_id:
          type: integer
        patient_id:
          type: integer
        location:
          type: string
        etiology:
          type: string
        depth_of_injury:
          type: string
        stage:
          type: string
        chronicity:
          type: string
        healing_status:
          type: string
        return_to_clinic:
          type: boolean
        infection_pain:
          type: object
        tissue_status:
          type: object
        vitals:
          type: object
        wound_condition:
          type: object
        exudate:
          type: object
        treatment:
          type: object

    FullAssessmentResponse:
      type: object
      properties:
        assessment_id:
          type: integer
        assessment_date:
          type: string
          format: date-time
        patient_id:
          type: integer
        patient_name:
          type: string
        clinician_id:
          type: integer
        clinician_name:
          type: string
        location:
          type: string
        etiology:
          type: string
        stage:
          type: string
        healing_status:
          type: string
        pain_score:
          type: string
        granulation_percent:
          type: integer
        length:
          type: number
        width:
          type: number

    WoundHistory:
      type: object
      properties:
        assessment_id:
          type: integer
        assessment_date:
          type: string
          format: date-time
        location:
          type: string
        stage:
          type: string
        healing_status:
          type: string

    PaginatedPatientsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Patient'
        page:
          type: integer
        page_size:
          type: integer
        total_count:
          type: integer
        total_pages:
          type: integer

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

    SuccessResponse:
      type: object
      properties:
        message:
          type: string
        data:
          type: object